const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('homeApi', {
  loadConfig: () => ipcRenderer.invoke('config:load'),
  saveConfig: (config) => ipcRenderer.invoke('config:save', config),
  backupConfig: (config) => ipcRenderer.invoke('config:backup', config),
  restoreConfig: () => ipcRenderer.invoke('config:restore'),
  chooseLocalEntry: (kind) => ipcRenderer.invoke('entry:choose-local', kind),
  validateEntry: (entry) => ipcRenderer.invoke('entry:validate', entry),
  entryIcon: (entryId) => ipcRenderer.invoke('entry:icon', entryId),
  chooseWallpaper: () => ipcRenderer.invoke('wallpaper:choose'),
  launchEntry: (entry) => ipcRenderer.invoke('entry:launch', entry),
  copyEntryPath: (entryId) => ipcRenderer.invoke('entry:copy-path', entryId),
  chooseAudioFiles: () => ipcRenderer.invoke('audio:choose'),
  audioUrl: (trackId) => ipcRenderer.invoke('audio:url', trackId),
  reportMusicState: (value) => ipcRenderer.send('music:state', value),
  onMusicCommand: (callback) => ipcRenderer.on('music:command', (_event, command) => callback(command)),
  didaStatus: () => ipcRenderer.invoke('dida:status'),
  didaDashboard: () => ipcRenderer.invoke('dida:dashboard'),
  connectDida: (write = false) => ipcRenderer.invoke('dida:connect', write === true),
  completeDidaTask: (projectId, taskId, occurrence) => ipcRenderer.invoke('dida:complete', projectId, taskId, occurrence),
  disconnectDida: () => ipcRenderer.invoke('dida:disconnect'),
  setHotkey: (accelerator) => ipcRenderer.invoke('app:set-hotkey', accelerator),
  startupSettings: () => ipcRenderer.invoke('app:startup-settings'),
  saveStartupSettings: (settings) => ipcRenderer.invoke('app:save-startup-settings', settings),
  about: () => ipcRenderer.invoke('app:about'),
  pageReady: () => ipcRenderer.send('app:page-ready'),
  hide: () => ipcRenderer.invoke('app:hide'),
  performTransition: (action) => ipcRenderer.invoke('app:perform-transition', action),
  onRequestTransition: (callback) => ipcRenderer.on('app:request-transition', (_event, action) => callback(action)),
  onNotice: (callback) => ipcRenderer.on('app:notice', (_event, message) => callback(message)),
  onDesktopTrialAttached: (callback) => ipcRenderer.on('desktop-trial:attached', (_event, status) => callback(status)),
  calendarState: () => ipcRenderer.invoke('calendar:state'),
  reportCalendarState: (value) => ipcRenderer.send('calendar:state', value),
  onCalendarCheck: (callback) => ipcRenderer.on('calendar:check', () => callback()),
  windowState: () => ipcRenderer.invoke('app:window-state')
});
