// Isolated Electron regression run. Never loads the user's profile or Dida credentials.
const { app, BrowserWindow, ipcMain, shell } = require('electron');
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const { validateEntry, launchValidatedEntry } = require('../local-entry.cjs');
const root = path.resolve(__dirname, '../../..', 'work/entry-smoke');
app.setPath('userData', path.join(root, 'profile'));
app.disableHardwareAcceleration();
app.on('window-all-closed', () => {});
let saved = null, failSave = false, launches = 0, picks = 0;
const report = [];
const fixture = path.join(root, '中文 space.txt');
const configFile = path.join(root, 'config.json');
const check = (value, message) => { assert.ok(value, message); report.push(message); };
app.whenReady().then(async () => {
  await fs.mkdir(root, { recursive: true });
  await fs.writeFile(fixture, 'Synthetic entry regression fixture. No personal data.');
  ipcMain.handle('config:load', async () => ({ config: saved, recovered: false }));
  ipcMain.handle('config:save', async (_e, config) => {
    if (failSave) throw new Error('Synthetic save failure');
    await fs.writeFile(configFile, JSON.stringify(config));
    saved = JSON.parse(await fs.readFile(configFile, 'utf8'));
    return true;
  });
  ipcMain.handle('app:set-hotkey', () => ({ ok: true }));
  ipcMain.handle('dida:status', () => ({ state:'unconnected', message:'示例测试：未连接' }));
  ipcMain.handle('dida:dashboard', () => ({ source:'none', tasks:[], projects:[] }));
  ipcMain.handle('entry:choose-local', async (_e, kind) => { picks++; return { kind, target:fixture, canceled:false }; });
  ipcMain.handle('entry:validate', (_e, entry) => validateEntry(entry));
  ipcMain.handle('entry:launch', async (_e, entry) => {
    if(entry.kind === 'application') return launchValidatedEntry(entry, shell);
    const result = await launchValidatedEntry(entry, { openPath: async (target) => { assert.equal(target, fixture); launches++; return ''; } });
    return result;
  });
  let win;
  const open = async () => {
    win = new BrowserWindow({ show:false, width:900, height:760, webPreferences:{ preload:path.resolve(__dirname,'../preload.cjs'), contextIsolation:true, sandbox:true } });
    await win.loadFile(path.resolve(__dirname,'../src/index.html'));
    await win.webContents.executeJavaScript('load()');
  };
  const js = (source) => win.webContents.executeJavaScript(source, true);
  await open();
  await js("startEdit();buildEntryDialog({area:'apps',id:null});");
  check(await js("$('#entryMode').value==='application' && getComputedStyle($('#chooseTarget')).display!=='none'"), 'new software entry opens in application mode with visible picker');
  await js("$('#entryMode').value='demo';setTargetControls()");
  check(await js("getComputedStyle($('#targetRow')).display==='none'"), 'demo mode truly hides address controls (CSS regression)');
  await js("$('#entryTarget').value='https://example.com';$('#entryName').value='Example';saveEntry()");
  check(await js("$('#entryDialog').open && $('#entryError').textContent.length>0"), 'demo mode cannot silently discard typed address');
  await js("$('#entryMode').value='file';setTargetControls();chooseTarget()");
  check(picks === 1, 'picker button handler reaches IPC and returns selected path');
  await js("$('#entryName').value='中文 example';$('#search').value='nonmatching';saveEntry()");
  check(await js("!$('#entryDialog').open && $('#search').value===''"), 'saved entry is visible despite previous search');
  await js('stopEdit(true)');
  const id = Object.keys(saved.library).find(key => saved.library[key].name === '中文 example');
  check(saved.library[id].target === fixture, 'chosen path survives layout save to disk');
  win.destroy();
  saved = JSON.parse(await fs.readFile(configFile,'utf8'));
  await open();
  check(await js(`entry(${JSON.stringify(id)}).target===${JSON.stringify(fixture)}`), 'entry survives renderer restart and config reload');
  await js(`activateEntry(${JSON.stringify(id)})`);
  check(launches === 1, 'homepage click passes saved target through production validation to launcher');
  await js(`startEdit();buildEntryDialog({area:'apps',id:${JSON.stringify(id)}});$('#entryTarget').value=${JSON.stringify('"' + fixture + '"')};saveEntry()`);
  await js('stopEdit(true)');
  check(saved.library[id].target === fixture, 'pasted quoted Chinese/space path is normalized and retained');
  await js("startEdit();state.library.zotero.name='unsaved';");
  failSave = true;
  await js('stopEdit(true)');
  check(await js("editing && state.library.zotero.name==='unsaved'"), 'save failure retains draft and edit mode');
  failSave = false;
  await js('stopEdit(false)');
  check(await js("state.library.zotero.name==='Zotero'"), 'cancel restores original config');
  await js(`startEdit();buildEntryDialog({area:'apps',id:${JSON.stringify(id)}});$('#entryTarget').value='C:\\\\missing-entry-fixture-714.txt';saveEntry()`);
  check(await js("$('#entryDialog').open && $('#entryError').textContent.length>0"), 'invalid target remains in dialog with visible error');
  check(!(await validateEntry({kind:'file',target:'D:\\K science\\R 软件资料\\never-read.txt'})).ok, 'forbidden target rejected before filesystem lookup');
  check(!(await validateEntry({kind:'application',target:'C:\\shortcut.lnk'})).ok, 'shortcut rejected without resolving its target');
  check((await validateEntry({kind:'website',target:'https://example.com/'})).ok, 'website target validation');
  await js("$('#entryDialog').close();stopEdit(false)");
  const calculator=path.join(process.env.SystemRoot,'System32','calc.exe');
  await js(`startEdit();buildEntryDialog({area:'apps',id:null});$('#entryName').value='Synthetic Calculator';$('#entryTarget').value=${JSON.stringify(calculator)};saveEntry()`);
  await js('stopEdit(true)');
  const calculatorId=Object.keys(saved.library).find(key=>saved.library[key].name==='Synthetic Calculator');
  check(!!calculatorId,'application exe path validates and saves');
  const result=await js(`window.homeApi.launchEntry({kind:entry(${JSON.stringify(calculatorId)}).kind,target:entry(${JSON.stringify(calculatorId)}).target})`);
  check(result.ok,'real Windows shell accepts saved Calculator application launch');
  win.destroy();
  await fs.writeFile(path.join(root,'report.json'), JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
  app.quit();
}).catch(async error => {
  console.error(error);
  await fs.mkdir(root,{recursive:true});
  await fs.writeFile(path.join(root,'failure.txt'),String(error.stack));
  app.exit(1);
});
